### ISSUE TITLE
[Bug?]: Tailwind CSS v4 outputs `&` as `&amp;` which breaks the styles

### ISSUE THREAD

**Issue by DaniGuardiola** [solidjs/solid-start#1749]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Current behavior 😯

Tailwind CSS v4 (recently fixed to work with Solid Start) outputs `&` as `&amp;` which breaks the styles.

For example, a class using a "dark theme" variant like this:

```css
.dark\:bg-red-500 {
  &:where(.dark, .dark *) {
    background-color: var(--color-red-500);
  }
}
```

This is actually outputted like this:

```css
.dark\:bg-red-500 {
  &amp;:where(.dark, .dark *) {
    background-color: var(--color-red-500);
  }
}
```

### Expected behavior 🤔

Outputs `&` directly.

### Steps to reproduce 🕹

See repro: https://github.com/solidjs/solid-start/pull/1748

### Context 🔦

It doesn't depend on the vite setup because it also happened with the alternative PostCSS-based setup. Unsure if the issue is on Solid Start's side or Tailwind CSS's side.

Related Tailwind CSS issue: https://github.com/tailwindlabs/tailwindcss/issues/16133

**Comment by DaniGuardiola** [comment]
Reading through some of the links [here](https://github.com/tailwindlabs/tailwindcss/issues/16133#issuecomment-2643263860), it seems like a potential solution/workaround would be to have the tailwind vite plugin before the solid start (vinxi?) one. How can this be achieved in Solid Start?

Update: I just tried forcing the ordering to `"pre"`, but it doesn't seem to make sense because `tailwind()` actually returns a series of plugins that already have this setting. Not sure what else to try.

**Comment by atilafassina** [comment]
Since [Release 1.1.0 - Gear 5](https://github.com/solidjs/solid-start/releases/tag/%40solidjs%2Fstart%401.1.0), the template was bumped and Tailwind v4 support was added. Are we able to close this one, @DaniGuardiola  / @birkskyum ?

**Comment by irisarco** [comment]
I've encountered the same bug, my case is quite simple:

```html
<input class="placeholder:text-red-500" placeholder="I should be red" />
```

Placeholder won't be red and this is the generated CSS:

```css
.placeholder\:text-red-500 {
  &amp;::placeholder {
    color: var(--color-red-500);
  }
}
```

This bug is still present on the new release.
