### ISSUE TITLE
Bug: Miniflare refuses to inject D1 Database with Cloudflare Pages adapter.

### ISSUE THREAD

**Issue by izznatsir** [solidjs/solid-start#476]
`vite.config.js`:
```typescript
import solid from "solid-start/vite";
import pages from "solid-start-cloudflare-pages";
import { defineConfig } from "vite";

export default defineConfig({
	plugins: [
		solid({
			adapter: pages({
				wranglerConfigPath: true,
			}),
		}),
	],
});
```

`wrangler.toml`
```toml
compatibility_date = "2022-11-20"

[[d1_databases]]
binding = "DB"
database_name = "EXAMPLE"
database_id = "####"
```

`console`
![Screenshot from 2022-11-24 13-57-25](https://user-images.githubusercontent.com/32354148/203715652-0695782e-bd68-43e3-904d-5f007e136eff.png)

Versions:
NodeJS: 18.2.1
pnpm: 7.17.0
solid-start: 0.2.0
solid-start-cloudlfare-pages: 0.2.5
